-- ═══════════════════════════════════════════════════════════════════
-- Миграция 004: разделение статусов автоматов + локации + история размещений
-- P0.4 (корректировки №2 и №4) · Аддитивная
-- ═══════════════════════════════════════════════════════════════════

-- ─── Три независимых статуса (корректировка №2) ────────────────────
-- operating_status: эксплуатационный (где автомат в жизненном цикле)
-- tech_status: техническое состояние (ТОЛЬКО из телеметрии/ручной отметки, НЕ из продаж)
-- sales_activity: НЕ хранится — вычисляется из wash_transactions (active/quiet/dormant)
alter table machines add column if not exists operating_status text not null default 'active'
  check (operating_status in ('active','storage','relocating','office','retired','unknown'));
alter table machines add column if not exists tech_status text not null default 'unknown'
  check (tech_status in ('online','offline','repair','unknown'));
alter table machines add column if not exists installed_date date;
alter table machines add column if not exists responsible text;
-- Легаси-колонка machines.status сохраняется до перевода UI (Фаза 1), затем deprecated

-- Перенос данных: статусы из листа «Платные мойки» — это операционные отметки партнёра.
-- Online → tech_status='online' (отметка человека, не телеметрия — честно фиксируем в notes)
-- OFFLINE → tech_status='offline'; Office → operating_status='office'
-- 28 автоматов без локации → operating_status='unknown' (НЕ offline!)
-- (выполняется скриптом сидирования после применения, данные из mapping.json)

-- ─── Локации ───────────────────────────────────────────────────────
create table if not exists locations (
  id            bigint generated by default as identity primary key,
  name          text not null unique,
  chain         text,                          -- Circle K / Alfamart / Ithon Mart / прочее
  address       text,
  city          text default 'Бали',
  country       text default 'Индонезия',
  maps_url      text,
  rent_amount   numeric,                       -- null = аренда неизвестна (DATA INCOMPLETE)
  rent_currency text not null default 'IDR',
  promo_price   boolean default false,
  source        text not null default 'imported'
    check (source in ('live','imported','manual','demo')),
  created_at    timestamptz default now()
);

-- ─── История размещений (корректировка №4) ─────────────────────────
-- Мойка атрибуцируется к локации, действовавшей на дату транзакции:
-- join wash_transactions.tx_at between from_date and coalesce(to_date, 'infinity')
create table if not exists machine_location_history (
  id          bigint generated by default as identity primary key,
  machine     text not null references machines(id) on delete cascade,
  location_id bigint references locations(id) on delete set null,
  from_date   date not null,
  to_date     date,                            -- null = текущее размещение
  note        text,
  created_at  timestamptz default now()
);
create unique index if not exists one_open_placement
  on machine_location_history(machine) where to_date is null;
create index if not exists mlh_machine_dates on machine_location_history(machine, from_date);

-- Сидирование: 52 локации из маппинга + текущие размещения
-- (from_date = дата первой транзакции автомата; выполняется скриптом после 005)

-- Аудит новых таблиц
do $$
declare t text;
begin
  foreach t in array array['locations','machine_location_history'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "open_access" on %I', t);
    execute format('create policy "open_access" on %I for all using (true) with check (true)', t);
    execute format('drop trigger if exists audit_%I on %I', t, t);
    execute format('create trigger audit_%I after insert or update or delete on %I
                    for each row execute function public.audit_change()', t, t);
  end loop;
end $$;
-- open_access временный — закрывается в 007

notify pgrst, 'reload schema';

-- ═══ ОТКАТ (migration-004-down) ════════════════════════════════════
-- drop table machine_location_history;
-- drop table locations;
-- alter table machines drop column operating_status, drop column tech_status,
--   drop column installed_date, drop column responsible;
