-- ═══════════════════════════════════════════════════════════════════
-- Миграция 006: движок задач (реляционный) + базовые финансы (cash-in)
-- P0.4 (корректировки №5, №6, №7) · Аддитивная
-- ═══════════════════════════════════════════════════════════════════

-- ─── Задачи (корректировка №5: без JSONB-истории) ──────────────────
create table if not exists tasks (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  department  text,
  object_type text,                       -- machine|location|lead|advertiser|contract|campaign|project|incident|employee
  object_id   text,
  assignee    uuid references profiles(id) on delete set null,
  creator     uuid references profiles(id) on delete set null,
  priority    text not null default 'medium' check (priority in ('critical','high','medium','low')),
  deadline    date,
  status      text not null default 'new' check (status in ('new','in_progress','blocked','done','cancelled')),
  kpi_link    text,
  expected_result text,                   -- поправка №3: какой результат ожидается
  actual_result   text,                   -- что получилось по факту (заполняется при закрытии)
  done_at     timestamptz,
  source      text not null default 'manual' check (source in ('manual','alert','auto')),
  created_at  timestamptz default now()
);
-- OVERDUE не хранится: вычисляется как status not in ('done','cancelled') and deadline < current_date
create index if not exists tasks_assignee on tasks(assignee, status);
create index if not exists tasks_object on tasks(object_type, object_id);
create index if not exists tasks_deadline on tasks(deadline) where status not in ('done','cancelled');

create table if not exists task_comments (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  author     uuid references profiles(id) on delete set null,
  body       text not null,
  created_at timestamptz default now()
);

create table if not exists task_attachments (
  id          bigint generated by default as identity primary key,
  task_id     bigint not null references tasks(id) on delete cascade,
  filename    text not null,
  url         text,
  uploaded_by uuid references profiles(id) on delete set null,
  created_at  timestamptz default now()
);

create table if not exists task_activity (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  actor      uuid references profiles(id) on delete set null,
  action     text not null,               -- created|status_changed|assigned|deadline_changed|priority_changed
  old_value  text,
  new_value  text,
  created_at timestamptz default now()
);

-- ─── Финансы: счета и поступления (корректировки №6, №7) ───────────
create table if not exists invoices (
  id           bigint generated by default as identity primary key,
  kind         text not null check (kind in ('wash','dooh','franchise','other')),
  counterparty text not null,
  object_type  text,                      -- franchise_lead | dooh_contract | machine | ...
  object_id    text,
  amount       numeric not null,
  currency     text not null default 'IDR',
  issued_date  date,
  due_date     date,
  status       text not null default 'draft'
    check (status in ('draft','sent','paid','partially_paid','overdue','cancelled')),
  notes        text,
  source       text not null default 'manual' check (source in ('live','imported','manual','demo')),
  created_at   timestamptz default now()
);
-- OVERDUE-дебиторка: status in ('sent','partially_paid') and due_date < current_date

-- Поправка №4: payment_method, external_reference, source, currency + original amount
create table if not exists payments (
  id                bigint generated by default as identity primary key,
  invoice_id        bigint references invoices(id) on delete set null,
  kind              text not null check (kind in ('wash','dooh','franchise','other')),
  counterparty      text,
  object_type       text,
  object_id         text,
  amount            numeric not null,               -- учётная сумма (в currency)
  currency          text not null default 'IDR',
  original_amount   numeric,                        -- если оплата пришла в другой валюте
  original_currency text,
  received_at       date not null,
  payment_method    text,                           -- transfer | midtrans | cash | ...
  external_reference text,                          -- № платёжки / ID транзакции провайдера
  source            text not null default 'manual' check (source in ('live','imported','manual','demo')),
  created_at        timestamptz default now(),
  check ((original_amount is null) = (original_currency is null))
);
create index if not exists payments_kind_at on payments(kind, received_at);

-- ─── Дисциплина воронки франшизы (корректировка №7) ────────────────
-- Новые этапы в конце воронки: signed → deposit_paid → fully_paid (cash-in = из payments)
alter table franchise_leads add column if not exists next_action text;
alter table franchise_leads add column if not exists next_action_date date;
alter table franchise_leads add column if not exists deal_value numeric;
alter table franchise_leads add column if not exists deal_currency text not null default 'IDR';
alter table franchise_leads add column if not exists probability int;
alter table franchise_leads add column if not exists signed_date date;
alter table franchise_leads add column if not exists source_channel text;
alter table franchise_leads add column if not exists last_activity_at timestamptz;
-- Cash-in по лиду = sum(payments where object_type='franchise_lead' and object_id=lead.id)
-- KPI ком. директора считать ТОЛЬКО от payments.received_at (фактические деньги)

-- RLS (временно open, закрытие в 007) + аудит финансовых таблиц и задач
do $$
declare t text;
begin
  foreach t in array array['tasks','task_comments','task_attachments','task_activity',
                           'invoices','payments'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "open_access" on %I', t);
    execute format('create policy "open_access" on %I for all using (true) with check (true)', t);
  end loop;
  foreach t in array array['tasks','invoices','payments'] loop
    execute format('drop trigger if exists audit_%I on %I', t, t);
    execute format('create trigger audit_%I after insert or update or delete on %I
                    for each row execute function public.audit_change()', t, t);
  end loop;
end $$;

notify pgrst, 'reload schema';

-- ═══ ОТКАТ (migration-006-down) ════════════════════════════════════
-- drop table task_activity; drop table task_attachments; drop table task_comments; drop table tasks;
-- drop table payments; drop table invoices;
-- alter table franchise_leads drop column next_action, drop column next_action_date,
--   drop column deal_value, drop column deal_currency, drop column probability,
--   drop column signed_date, drop column source_channel, drop column last_activity_at;
