-- ═══════════════════════════════════════════════════════════════════
-- Миграция 003: профили пользователей (Supabase Auth) + Audit Log
-- P0.1 + P0.3 · Аддитивная, ничего не ломает
-- ═══════════════════════════════════════════════════════════════════

-- ─── Профили сотрудников (привязка к auth.users) ───────────────────
create table if not exists profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text unique not null,
  name       text not null,
  role       text not null default 'ops' check (role in
    ('ceo','coo','commercial_director','marketing','franchise_sales','dooh_sales',
     'tech_manager','technician','finance','legal','dev','ops','admin')),
  avatar     text,
  active     boolean not null default true,
  created_at timestamptz default now()
);

-- Роль текущего пользователя (для RLS-политик)
create or replace function public.user_role() returns text
language sql stable security definer set search_path = public as
$$ select role from profiles where id = auth.uid() and active $$;

-- Автосоздание профиля при регистрации (роль по умолчанию ops, admin меняет)
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── Audit Log ─────────────────────────────────────────────────────
create table if not exists audit_log (
  id          bigint generated by default as identity primary key,
  actor       uuid,
  actor_email text,
  action      text not null,          -- INSERT / UPDATE / DELETE
  table_name  text not null,
  object_id   text,
  old_data    jsonb,
  new_data    jsonb,
  at          timestamptz default now()
);
create index if not exists audit_log_table_at on audit_log(table_name, at desc);

create or replace function public.audit_change() returns trigger
language plpgsql security definer set search_path = public as $$
declare oid text;
begin
  oid := coalesce(
    case when tg_op = 'DELETE' then (to_jsonb(old)->>'id') else (to_jsonb(new)->>'id') end, '');
  insert into audit_log (actor, actor_email, action, table_name, object_id, old_data, new_data)
  values (
    auth.uid(),
    coalesce((select email from profiles where id = auth.uid()), 'anon/system'),
    tg_op, tg_table_name, oid,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end $$;

-- Аудит чувствительных таблиц (существующие; новые подключаются в своих миграциях)
do $$
declare t text;
begin
  foreach t in array array['machines','franchise_leads','legal_contracts','contractors',
                           'app_settings','profiles']
  loop
    execute format('drop trigger if exists audit_%I on %I', t, t);
    execute format('create trigger audit_%I after insert or update or delete on %I
                    for each row execute function public.audit_change()', t, t);
  end loop;
end $$;

-- RLS для новых таблиц (open_access пока НЕ трогаем — закрытие в 007)
alter table profiles enable row level security;
drop policy if exists profiles_read on profiles;
create policy profiles_read on profiles for select using (auth.role() = 'authenticated');
drop policy if exists profiles_admin_write on profiles;
create policy profiles_admin_write on profiles for all
  using (public.user_role() = 'admin') with check (public.user_role() = 'admin');

alter table audit_log enable row level security;
drop policy if exists audit_read on audit_log;
create policy audit_read on audit_log for select
  using (public.user_role() in ('ceo','admin'));
-- Запись в audit_log только через security definer триггер — политик на запись нет

notify pgrst, 'reload schema';

-- ═══ ОТКАТ (migration-003-down) ════════════════════════════════════
-- drop trigger on_auth_user_created on auth.users;
-- drop function handle_new_user();
-- do $$ declare t text; begin
--   foreach t in array array['machines','franchise_leads','legal_contracts','contractors','app_settings','profiles']
--   loop execute format('drop trigger if exists audit_%I on %I', t, t); end loop; end $$;
-- drop function audit_change();
-- drop table audit_log;
-- drop function user_role();
-- drop table profiles;
