-- ═══════════════════════════════════════════════════════════════════
-- Миграция 005: транзакции моек + идемпотентный импорт
-- P0.4 (корректировка №3) · Аддитивная
-- Единственный источник правды по мойкам = wash_transactions.
-- machine_monthly и wash_stats становятся ПРОИЗВОДНЫМИ кэшами.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists import_log (
  id            bigint generated by default as identity primary key,
  filename      text,
  source        text not null default 'xlsx',
  imported_by   uuid,
  rows_total    int default 0,
  rows_inserted int default 0,
  rows_skipped  int default 0,                 -- дубликаты doc_number = идемпотентность
  period_from   date,
  period_to     date,
  at            timestamptz default now()
);

create table if not exists wash_transactions (
  id              bigint generated by default as identity primary key,
  -- Поправка №1: идемпотентность = источник + внешний ID документа
  source_system   text not null default 'vending_xlsx',   -- vending_xlsx | vending_api | manual
  external_doc_id text not null,                          -- F-CK2502003566
  machine         text not null references machines(id),
  tx_at          timestamptz not null,
  qty            numeric not null default 1,
  amount         numeric not null default 0,
  currency       text not null default 'IDR',
  product        text,
  payment_method text,
  tx_type        text not null default 'sale'
    check (tx_type in ('sale','storage','other')),   -- Sales outbound / Other storage / Other outbound
  wash_kind      text
    check (wash_kind in ('paid','free','coupon')),   -- только для tx_type='sale'
  source         text not null default 'imported'
    check (source in ('live','imported','manual','demo')),
  import_id      bigint references import_log(id) on delete set null,
  created_at     timestamptz default now(),
  constraint wt_source_doc_unique unique (source_system, external_doc_id)
);
create index if not exists wt_machine_at on wash_transactions(machine, tx_at);
create index if not exists wt_at on wash_transactions(tx_at);
create index if not exists wt_kind on wash_transactions(tx_type, wash_kind);

-- Импорт: insert ... on conflict (source_system, external_doc_id) do nothing →
-- повторная загрузка того же файла не создаёт дублей (rows_skipped в import_log)

-- ─── Разделение платных/промо в агрегатах (§8 ТЗ) ──────────────────
alter table wash_stats add column if not exists w_paid int default 0;
alter table wash_stats add column if not exists w_promo int default 0;
alter table machine_monthly add column if not exists w_paid int default 0;
alter table machine_monthly add column if not exists w_promo int default 0;

-- ─── Пересборка производных агрегатов из транзакций ────────────────
-- Вызывается после каждого импорта (RPC). Security definer: выполняется
-- под правами владельца, política на прямую запись в кэши не нужна.
create or replace function public.refresh_wash_aggregates() returns void
language plpgsql security definer set search_path = public as $$
begin
  -- Помесячно по автоматам
  delete from machine_monthly;
  insert into machine_monthly (machine, month, w, r, w_paid, w_promo)
  select machine, to_char(tx_at, 'YYYY-MM'),
         count(*) filter (where tx_type='sale'),
         coalesce(sum(amount) filter (where tx_type='sale'), 0),
         count(*) filter (where tx_type='sale' and wash_kind='paid'),
         count(*) filter (where tx_type='sale' and wash_kind in ('free','coupon'))
  from wash_transactions group by 1, 2;

  -- Дневная динамика сети: последние 90 дней
  delete from wash_stats;
  insert into wash_stats (d, w, r, w_paid, w_promo)
  select to_char(tx_at::date, 'DD.MM'),
         count(*) filter (where tx_type='sale'),
         coalesce(sum(amount) filter (where tx_type='sale'), 0),
         count(*) filter (where tx_type='sale' and wash_kind='paid'),
         count(*) filter (where tx_type='sale' and wash_kind in ('free','coupon'))
  from wash_transactions
  where tx_at >= now() - interval '90 days'
  group by tx_at::date order by tx_at::date;

  -- Сводка в карточках автоматов (wd/wm/rd/rm/wt/rt/last_wash)
  update machines m set
    wt = coalesce(s.wt, 0), rt = coalesce(s.rt, 0), last_wash = s.last_wash,
    wm = coalesce(s.wm, 0), rm = coalesce(s.rm, 0),
    wd = coalesce(s.wd, 0), rd = coalesce(s.rd, 0)
  from (
    select machine,
      count(*) filter (where tx_type='sale') wt,
      sum(amount) filter (where tx_type='sale') rt,
      max(tx_at::date) filter (where tx_type='sale') last_wash,
      count(*) filter (where tx_type='sale' and tx_at >= now() - interval '30 days') wm,
      coalesce(sum(amount) filter (where tx_type='sale' and tx_at >= now() - interval '30 days'),0) rm,
      count(*) filter (where tx_type='sale' and tx_at::date = current_date) wd,
      coalesce(sum(amount) filter (where tx_type='sale' and tx_at::date = current_date),0) rd
    from wash_transactions group by machine
  ) s where s.machine = m.id;
end $$;

-- RLS (open_access временно, закрытие в 007) + аудит import_log
do $$
declare t text;
begin
  foreach t in array array['wash_transactions','import_log'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "open_access" on %I', t);
    execute format('create policy "open_access" on %I for all using (true) with check (true)', t);
  end loop;
end $$;

notify pgrst, 'reload schema';

-- ═══ ОТКАТ (migration-005-down) ════════════════════════════════════
-- drop function refresh_wash_aggregates();
-- drop table wash_transactions;
-- drop table import_log;
-- alter table wash_stats drop column w_paid, drop column w_promo;
-- alter table machine_monthly drop column w_paid, drop column w_promo;
-- (кэши machine_monthly/wash_stats/machines.* сохраняют последние значения — данные не теряются)
