-- ═══════════════════════════════════════════════════════════════════
-- Миграция 002: помесячная статистика моек по автоматам
-- Запустить в Supabase SQL Editor после schema.sql
-- ═══════════════════════════════════════════════════════════════════

-- Итоговые показатели за всё время — прямо в карточке автомата
alter table machines add column if not exists wt int default 0;          -- моек всего
alter table machines add column if not exists rt numeric default 0;      -- выручка всего
alter table machines add column if not exists last_wash date;            -- дата последней мойки

-- Помесячная статистика: одна строка = автомат + месяц
drop table if exists machine_monthly;
create table machine_monthly (
  id         bigint generated by default as identity primary key,
  machine    text references machines(id) on delete cascade,
  month      text not null,                 -- 'YYYY-MM'
  w          int default 0,                 -- моек за месяц
  r          numeric default 0,             -- выручка за месяц
  created_at timestamptz default now()
);

alter table machine_monthly enable row level security;
drop policy if exists "open_access" on machine_monthly;
create policy "open_access" on machine_monthly for all using (true) with check (true);

notify pgrst, 'reload schema';
