-- ═══════════════════════════════════════════════════════════════════
-- Helm Care CRM — схема базы данных (Supabase / PostgreSQL)
-- Запускать в Supabase: SQL Editor → New query → вставить → Run
-- Скрипт можно запускать повторно — он пересоздаёт таблицы заново.
-- ═══════════════════════════════════════════════════════════════════

drop table if exists machine_logs;
drop table if exists wash_stats;
drop table if exists content_items;
drop table if exists notifications;
drop table if exists clients;
drop table if exists dev_projects;
drop table if exists legal_contracts;
drop table if exists franchise_leads;
drop table if exists contractors;
drop table if exists campaigns;
drop table if exists machines;
drop table if exists technicians;
drop table if exists app_settings;

-- ─── Техники ────────────────────────────────────────────────────────
create table technicians (
  id         bigint generated by default as identity primary key,
  name       text not null,
  phone      text,
  telegram   text,
  active     boolean default true,
  created_at timestamptz default now()
);

-- ─── Автоматы ───────────────────────────────────────────────────────
create table machines (
  id            text primary key,            -- "AW-001"
  place         text not null,               -- название места
  addr          text,                        -- адрес
  country       text,
  city          text,
  district      text,
  status        text default 'online',       -- online | offline | repair
  wd            int  default 0,              -- моек сегодня
  wm            int  default 0,              -- моек за месяц
  rd            numeric default 0,           -- выручка сегодня
  rm            numeric default 0,           -- выручка за месяц
  up            numeric default 100,         -- uptime %
  dt            int default 0,               -- часов простоя
  rent          numeric default 0,           -- аренда/мес
  rent_due      text,                        -- срок оплаты аренды
  ls            text,                        -- последнее ТО
  ns            text,                        -- следующее ТО
  tech          text,                        -- ответственный техник
  maps_url      text,
  photos        jsonb default '[]',
  install_date  text,
  relocation    boolean default false,
  notes         text,
  created_at    timestamptz default now()
);

-- ─── Маркетинговые кампании ─────────────────────────────────────────
create table campaigns (
  id          bigint generated by default as identity primary key,
  name        text not null,
  goal        text,
  channel     text,
  status      text default 'planned',        -- planned | active | completed
  start_date  text,
  end_date    text,
  budget      numeric default 0,
  spent       numeric default 0,
  exp_leads   int default 0,
  leads       int default 0,
  responsible text,
  result      text,
  approved    boolean default false,
  created_at  timestamptz default now()
);

-- ─── Контракторы (реклама на автоматах) ─────────────────────────────
create table contractors (
  id          bigint generated by default as identity primary key,
  company     text not null,
  brand       text,
  type        text,                          -- Баннер | Экран | Листовка
  machine     text references machines(id) on delete set null,
  price       numeric default 0,
  pay_form    text,
  paid        text default 'pending',        -- paid | pending | overdue
  due_date    text,
  moderated   boolean default false,
  start_date  text,
  end_date    text,
  contact     text,
  phone       text,
  responsible text,
  created_at  timestamptz default now()
);

-- ─── Лиды франшизы ──────────────────────────────────────────────────
create table franchise_leads (
  id         bigint generated by default as identity primary key,
  name       text not null,
  city       text,
  stage      text default 'new',             -- 13 стадий: new | contacted | qualification | presentation |
                                             -- proposal | negotiation | contract | closed_won |
                                             -- warm | longterm | not_qualified | lost | junk
  mach       int default 1,                  -- сколько автоматов интересует
  src        text,                           -- источник
  date       text,
  mgr        text,                           -- менеджер
  note       text,
  phone      text,
  created_at timestamptz default now()
);

-- ─── Юридические договоры ───────────────────────────────────────────
create table legal_contracts (
  id         bigint generated by default as identity primary key,
  type       text,                           -- Аренда | Франшиза | Реклама
  party      text not null,
  status     text default 'active',          -- active | expiring | dispute
  signed     text,
  expires    text,
  risk       text default 'low',             -- low | medium | high
  pay        text,
  created_at timestamptz default now()
);

-- ─── Проекты разработки ─────────────────────────────────────────────
create table dev_projects (
  id         bigint generated by default as identity primary key,
  name       text not null,
  status     text default 'planning',        -- planning | on_track | delayed | completed
  pct        int default 0,
  dl         text,                           -- дедлайн
  budget     numeric default 0,
  spent      numeric default 0,
  tasks      jsonb default '[]',
  created_at timestamptz default now()
);

-- ─── Клиенты (B2C, мойки шлемов) ───────────────────────────────────
create table clients (
  id         bigint generated by default as identity primary key,
  name       text not null,
  phone      text,
  email      text,
  city       text,
  district   text,
  source     text,
  gender     text,
  age        int,
  helmet     text,
  moped      text,
  vouchers   int default 0,
  washes     int default 0,
  joined     text,
  active     boolean default true,
  refs       int default 0,
  created_at timestamptz default now()
);

-- ─── Push-уведомления клиентам ─────────────────────────────────────
create table notifications (
  id         bigint generated by default as identity primary key,
  title      text not null,
  body       text,
  target     text default 'all',             -- all | geo | segment
  sent       int default 0,
  opened     int default 0,
  date       text,
  status     text default 'draft',           -- draft | scheduled | sent
  created_at timestamptz default now()
);

-- ─── Контент на автоматах (экраны) ─────────────────────────────────
create table content_items (
  id         bigint generated by default as identity primary key,
  name       text not null,
  type       text,                           -- image | video
  size       text,
  assigned   jsonb default '[]',             -- ["AW-001", ...]
  status     text default 'pending',         -- active | pending
  uploaded   text,
  created_at timestamptz default now()
);

-- ─── Статистика моек по дням ───────────────────────────────────────
create table wash_stats (
  id         bigint generated by default as identity primary key,
  d          text not null,                  -- дата "13.04"
  w          int default 0,                  -- моек
  r          numeric default 0,              -- выручка
  machine    text references machines(id) on delete cascade,
  created_at timestamptz default now()
);

-- ─── Логи устройств автоматов ──────────────────────────────────────
create table machine_logs (
  id         bigint generated by default as identity primary key,
  machine    text references machines(id) on delete cascade,
  device     text,
  error      text,
  level      text default 'info',            -- info | warning | critical
  time       text,
  resolved   boolean default false,
  created_at timestamptz default now()
);

-- ─── Настройки (тарифы и прочее) ───────────────────────────────────
create table app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz default now()
);

-- ═══ RLS: включаем и пока открываем полный доступ ═══════════════════
-- (на этапе внедрения Supabase Auth политики будут ужесточены по ролям)
do $$
declare t text;
begin
  foreach t in array array['technicians','machines','campaigns','contractors',
    'franchise_leads','legal_contracts','dev_projects','clients','notifications',
    'content_items','wash_stats','machine_logs','app_settings']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "open_access" on %I', t);
    execute format('create policy "open_access" on %I for all using (true) with check (true)', t);
  end loop;
end $$;

-- ═══ СТАРТОВЫЕ ДАННЫЕ ══════════════════════════════════════════════

insert into technicians (name, phone, telegram, active) values
  ('Козлов В.',   '+7 985 111-22-33', '@kozlov_tech',   true),
  ('Иванов А.',   '+7 916 444-55-66', '@ivanov_tech',   true),
  ('Петренко С.', '+7 903 777-88-99', '@petrenko_tech', false);

insert into machines (id, place, addr, status, wd, wm, rd, rm, up, dt, rent, ls, ns, tech, maps_url) values
  ('AW-001', 'ТЦ Европа',    'ул. Ленина, 12',     'online',  87,  2140, 8700,  214000, 99.2, 0,  18000, '12.04', '12.05', 'Козлов В.',   'https://maps.google.com'),
  ('AW-002', 'Пятёрочка',    'пр. Мира, 45',       'online',  64,  1680, 6400,  168000, 97.8, 0,  12000, '08.04', '08.05', 'Козлов В.',   'https://maps.google.com'),
  ('AW-003', 'Ост. Садовая', 'ул. Садовая, 7',     'offline', 0,   890,  0,     89000,  72.1, 14, 9000,  '01.04', '01.05', 'Иванов А.',   'https://maps.google.com'),
  ('AW-004', 'БЦ Победа',    'бул. Победы, 22',    'repair',  0,   1120, 0,     112000, 68.4, 48, 22000, '25.03', '25.04', 'Иванов А.',   'https://maps.google.com'),
  ('AW-005', 'ТЦ Горький',   'ул. Горького, 89',   'online',  112, 2890, 11200, 289000, 99.8, 0,  18000, '15.04', '15.05', 'Козлов В.',   'https://maps.google.com'),
  ('AW-006', 'АЗС Космос',   'пр. Космонавтов, 3', 'online',  45,  1290, 4500,  129000, 96.5, 0,  8000,  '10.04', '10.05', 'Петренко С.', 'https://maps.google.com');

insert into campaigns (name, goal, channel, status, start_date, end_date, budget, spent, exp_leads, leads, responsible, result, approved) values
  ('Meta — ретаргет апрель', 'Лиды на франшизу', 'Meta',   'active',    '01.04', '30.04', 80000, 54000, 100, 142, 'Смирнова К. И.', 'Перевыполнено +42%', true),
  ('Яндекс Директ апрель',   'Лиды автомойка',   'Яндекс', 'completed', '01.04', '30.04', 60000, 60000, 80,  98,  'Новиков С. А.',  'Выполнено +22.5%',   true),
  ('Акция Майские',          'Рост моек +20%',   'Мульти', 'planned',   '01.05', '10.05', 40000, 0,     60,  0,   'Волкова М. С.',  '—',                  false);

insert into contractors (company, brand, type, machine, price, pay_form, paid, due_date, moderated, start_date, end_date, contact, phone, responsible) values
  ('ООО Авторынок',   'АвтоДетали+',  'Баннер',   'AW-001', 8000,  'Предоплата',   'paid',    null,    true,  '01.04', '30.06', 'Иванов П.',   '+7 916 111-22-33', 'Смирнова К. И.'),
  ('ИП Кофе Бар',     'CoffeePoint',  'Экран',    'AW-001', 5000,  'Постоплата',   'paid',    '05.04', true,  '01.03', '31.05', 'Орлова К.',   '+7 925 333-44-55', 'Новиков С. А.'),
  ('Пицца-Хаус',      'PizzaHouse',   'Экран',    'AW-002', 6000,  'Отсрочка 14д', 'overdue', '05.04', true,  '01.04', '30.04', 'Грибов М.',   '+7 903 555-66-77', 'Смирнова К. И.'),
  ('Банк Открытие',   'Открытие',     'Баннер',   'AW-005', 12000, 'Предоплата',   'paid',    null,    true,  '01.02', '31.07', 'Белов А.',    '+7 985 777-88-99', 'Новиков С. А.'),
  ('Аптека Здоровье', 'ЗдоровьеПлюс', 'Листовка', 'AW-006', 4000,  'Предоплата',   'paid',    null,    false, '15.04', '15.07', 'Миронова Е.', '+7 916 999-00-11', 'Смирнова К. И.');

insert into franchise_leads (name, city, stage, mach, src, date, mgr, note, phone) values
  ('Абдулов Р.',    'Казань',       'negotiation',  3, 'Выставка',   '17.04', 'Новиков С. А.',  'Обсуждаем детали договора',  '+7 917 111-22-33'),
  ('ВелтГрупп',     'Новосибирск',  'proposal',     5, 'Таргет',     '15.04', 'Новиков С. А.',  'КП отправлено',              '+7 383 444-55-66'),
  ('Иванченко С.',  'Екатеринбург', 'contract',     2, 'Нетворкинг', '10.04', 'Смирнова К. И.', 'Договор на согласовании',    '+7 343 777-88-99'),
  ('ИП Мухамедов',  'Уфа',          'new',          1, 'Холодный',   '19.04', 'Новиков С. А.',  'Первый контакт',             '+7 927 555-11-22'),
  ('Ларина М.',     'Краснодар',    'presentation', 4, 'Таргет',     '14.04', 'Волкова М. С.',  'Зум назначен на 21.04',      '+7 918 222-33-44'),
  ('Синегуб П.',    'Ростов',       'warm',         2, 'Выставка',   '12.04', 'Новиков С. А.',  'Изучает условия',            '+7 863 999-88-77');

insert into legal_contracts (type, party, status, signed, expires, risk, pay) values
  ('Аренда',   'ТЦ Европа',  'active',   '12.01.2024', '12.01.2027', 'low',    'В срок'),
  ('Франшиза', 'Иванов С.',  'active',   '01.03.2024', '01.03.2027', 'low',    'В срок'),
  ('Аренда',   'БЦ Победа',  'expiring', '05.09.2023', '05.09.2026', 'medium', 'Задержка'),
  ('Реклама',  'Пицца-Хаус', 'expiring', '01.04.2026', '30.04.2026', 'low',    'Не опл.'),
  ('Аренда',   'АЗС Космос', 'dispute',  '14.07.2023', '14.07.2026', 'high',   'Спор');

insert into dev_projects (name, status, pct, dl, budget, spent, tasks) values
  ('Автомат v2.0',         'on_track',  65,  '01.09.2026', 850000, 420000, '["Механика","Электроника","ПО управления"]'),
  ('Мобильное приложение', 'delayed',   28,  '01.07.2026', 400000, 180000, '["iOS","Android","Backend API"]'),
  ('Собственная CRM',      'on_track',  40,  '01.10.2026', 150000, 130000, '["Supabase БД","CRUD","Авторизация"]'),
  ('API телеметрии v3',    'completed', 100, '15.04.2026', 120000, 115000, '["Протокол","Тесты","Деплой"]'),
  ('Система лояльности',   'planning',  5,   '01.11.2026', 600000, 12000,  '["Концепция","Дизайн","MVP"]');

insert into clients (name, phone, email, city, district, source, gender, age, helmet, moped, vouchers, washes, joined, active, refs) values
  ('Ахмад Ю.',  '+62 812-111-2233', 'ahmad@mail.com',  'Джакарта', 'Сентул',     'Instagram', 'М', 28, 'L',   'Honda Beat',     2, 14, '10.03.2026', true,  3),
  ('Карим Р.',  '+62 813-222-3344', 'karim@mail.com',  'Бандунг',  'Даго',       'Реклама',   'М', 34, 'XL',  'Yamaha NMAX',    1, 7,  '15.03.2026', true,  1),
  ('Дита С.',   '+62 821-333-4455', 'dita@mail.com',   'Джакарта', 'Pondok Ind', 'Друг',      'Ж', 25, 'M',   'Honda Scoopy',   3, 21, '01.02.2026', true,  7),
  ('Fajar H.',  '+62 857-444-5566', 'fajar@mail.com',  'Сурабая',  'Тенгах',     'Google',    'М', 31, 'L',   'Suzuki Address', 0, 3,  '01.04.2026', true,  0),
  ('Rini P.',   '+62 877-555-6677', 'rini@mail.com',   'Бали',     'Семиньяк',   'Instagram', 'Ж', 22, 'S',   'Honda Vario',    1, 9,  '20.03.2026', false, 2),
  ('Budi W.',   '+62 815-666-7788', 'budi@mail.com',   'Джакарта', 'Депок',      'Реклама',   'М', 41, 'XXL', 'Yamaha Aerox',   0, 2,  '15.04.2026', true,  0),
  ('Sari A.',   '+62 818-777-8899', 'sari@mail.com',   'Бандунг',  'Цимахи',     'Друг',      'Ж', 29, 'M',   'Honda PCX',      4, 28, '15.01.2026', true,  12),
  ('Hendra G.', '+62 851-888-9900', 'hendra@mail.com', 'Сурабая',  'Тенггилис',  'TikTok',    'М', 26, 'L',   'Yamaha Mio',     1, 6,  '05.04.2026', true,  1);

insert into notifications (title, body, target, sent, opened, date, status) values
  ('Акция — бесплатная мойка!',      'Только сегодня: 1 бесплатная мойка всем активным клиентам.',      'all',     847, 412, '15.04.2026', 'sent'),
  ('Рядом с вами новый аппарат',     'AW-007 запущен в вашем районе. Приходите!',                        'geo',     134, 89,  '12.04.2026', 'sent'),
  ('5 моек — получи ваучер',         'Вы уже сделали 5 моек! Ваучер на бесплатную мойку начислен.',      'segment', 203, 178, '10.04.2026', 'sent'),
  ('Майские праздники — скидка 20%', 'С 1 по 10 мая мойка шлема со скидкой 20%. Не пропустите!',        'all',     0,   0,   '01.05.2026', 'scheduled');

insert into content_items (name, type, size, assigned, status, uploaded) values
  ('Главный фон — мотоцикл',  'image', '2.4 МБ', '["AW-001","AW-002","AW-005"]', 'active',  '10.04.2026'),
  ('Промо-видео апрель',      'video', '18 МБ',  '["AW-001"]',                   'active',  '01.04.2026'),
  ('Фон — бренд Helm Care',   'image', '1.8 МБ', '["AW-006"]',                   'active',  '15.03.2026'),
  ('Видео инструкция мойки',  'video', '45 МБ',  '["AW-001","AW-002","AW-003","AW-004","AW-005","AW-006"]', 'active', '01.02.2026'),
  ('Акция майские праздники', 'image', '1.2 МБ', '[]',                           'pending', '20.04.2026');

insert into wash_stats (d, w, r) values
  ('13.04', 1620, 162000), ('14.04', 1740, 174000), ('15.04', 1580, 158000),
  ('16.04', 1810, 181000), ('17.04', 1890, 189000), ('18.04', 1750, 175000),
  ('19.04', 1842, 184200);

insert into machine_logs (machine, device, error, level, time, resolved) values
  ('AW-003', 'COM2 · Вентилятор внешний', 'Device timeout after 5s',           'critical', '19.04 · 14:32', false),
  ('AW-004', 'COM1 · УФ-лампа',           'No response on init',               'critical', '18.04 · 09:15', false),
  ('AW-003', 'COM3 · Помпа',              'Pressure drop detected',            'warning',  '18.04 · 11:40', false),
  ('AW-001', 'COM4 · Дозатор',            'Low fluid level warning',           'warning',  '17.04 · 16:20', true),
  ('AW-002', 'COM1 · УФ-лампа',           'Lamp life 80% used',                'info',     '16.04 · 08:00', true),
  ('AW-005', 'Payment · QR reader',       'Scan timeout 3s exceeded',          'warning',  '16.04 · 13:55', true),
  ('AW-006', 'App · Auto-update',         'Update v2.3.1 installed OK',        'info',     '15.04 · 02:00', true),
  ('AW-001', 'COM2 · Вентилятор',         'Speed variance ±12% normal range',  'info',     '14.04 · 17:30', true);

insert into app_settings (key, value) values
  ('pricing', '{
    "modes": [
      {"id":"basic",   "name":"Стандартная мойка", "basePrice":15000, "duration":8},
      {"id":"deep",    "name":"Глубокая очистка",  "basePrice":25000, "duration":15},
      {"id":"uv",      "name":"УФ-дезинфекция",    "basePrice":20000, "duration":10},
      {"id":"express", "name":"Экспресс 5 мин",    "basePrice":10000, "duration":5}
    ],
    "timeRules": [
      {"id":1, "name":"Ночной тариф", "days":["МО","ВТ","СР","ЧТ","ПТ","СБ","ВС"], "from":"23:00", "to":"06:00", "discount":-20, "color":"#3b82f6"},
      {"id":2, "name":"Час пик",      "days":["МО","ВТ","СР","ЧТ","ПТ"],           "from":"07:00", "to":"09:00", "discount":10,  "color":"#ef4444"},
      {"id":3, "name":"Обеденный",    "days":["МО","ВТ","СР","ЧТ","ПТ"],           "from":"12:00", "to":"14:00", "discount":-10, "color":"#10b981"},
      {"id":4, "name":"Выходной",     "days":["СБ","ВС"],                           "from":"09:00", "to":"21:00", "discount":-15, "color":"#818cf8"}
    ]
  }');
